// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWdLN8Dxpn96jQXyC3_XeTndObkzCMUZo',
    appId: '1:862227694572:web:c5d891d2f4ff1562f236c9',
    messagingSenderId: '862227694572',
    projectId: 'xoonideeplinker',
    authDomain: 'xoonideeplinker.firebaseapp.com',
    storageBucket: 'xoonideeplinker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCM00LwihOMX7RwF0tZk-RXWpb8ag22G0',
    appId: '1:862227694572:android:f69a8866bc92558cf236c9',
    messagingSenderId: '862227694572',
    projectId: 'xoonideeplinker',
    storageBucket: 'xoonideeplinker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvvLGpvZbZpzIxxVhZGE-BS2RGiab3KIk',
    appId: '1:862227694572:ios:b0d683accfd37a01f236c9',
    messagingSenderId: '862227694572',
    projectId: 'xoonideeplinker',
    storageBucket: 'xoonideeplinker.appspot.com',
    iosClientId: '862227694572-oak9lcu0j4m6s2ec884ll7kqkgi1i9in.apps.googleusercontent.com',
    iosBundleId: 'com.xooni.deeplinker',
  );
}
